-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'TASK_DEADLINE_SOON';
ALTER TYPE "NotificationType" ADD VALUE 'TASK_DEADLINE_TODAY';
ALTER TYPE "NotificationType" ADD VALUE 'TASK_DEADLINE_OVERDUE';
